[versions]
activity-compose = "1.7.2"
com-android-plugin = "8.0.2"
core = "1.10.1"
foundation = "1.4.3"
kotlin = "1.8.21"
kotlin-compose-compiler-extension = "1.4.7"
android-sdk-target = "33"
android-min-sdk = "28"
lifecycle-viewmodel = "2.6.1"
lifecycle-common = "2.6.1"
material = "1.4.3"
runtime = "1.4.3"
ui = "1.4.3"
[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity-compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-core = { module = "androidx.core:core", version.ref = "core" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "foundation" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle-viewmodel" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle-common" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
androidx-ui-unit = { module = "androidx.compose.ui:ui-unit", version.ref = "ui" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-plugin" }
com-android-library = { id = "com.android.library", version.ref = "com-android-plugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
com-google-gms-google-services = { id = "com.google.gms.google-services", version = "4.3.15" }
com_github_ben-manes_versions = { id = "com.github.ben-manes.versions", version = "0.47.0" }
io_gitlab_arturbosch_detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.0" }
com_autonomousapps_dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.20.0" }
org_jetbrains_kotlinx_kover = { id = "org.jetbrains.kotlinx.kover", version = "0.7.1" }
com_osacky_doctor = { id = "com.osacky.doctor", version = "0.8.1" }

[bundles]

