[versions]
activity-compose = "1.7.2"
com-android-plugin = "8.0.2"
core = "1.10.1"
foundation = "1.4.3"
kotlin = "1.8.21"
kotlin-compose-compiler-extension = "1.4.7"
android-sdk-target = "33"
android-min-sdk = "28"
lifecycle-viewmodel = "2.6.1"
lifecycle-common = "2.6.1"
coil-compose = "2.4.0"
lifecycle-runtime-ktx = "2.6.1"
navigation-compose = "2.6.0"
startup-runtime = "1.1.1"
material = "1.4.3"
moshi = "1.15.0"
javax-inject = "1"
appcompat = "1.6.1"
ksp = "1.8.21-1.0.11"
runtime = "1.4.3"
kotlinx-coroutines = "1.7.1"
ui = "1.4.3"
mockk = "1.13.5"
monitor = "1.6.1"
core-ktx = "1.10.1"
junit = "5.9.3"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
compose = "1.4.3"
room-runtime = "2.5.1"
sqlite = "2.3.1"
timber = "5.0.1"
com-google-android-material-material = "1.9.0"
hilt = "2.46.1"
retrofit = "2.9.0"
firebase-bom = "32.1.1"
okhttp = "4.11.0"
material3 = "1.1.0"
hilt-navigation-compose = "1.0.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity-compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-compose-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
androidx-compose-ui-unit = { module = "androidx.compose.ui:ui-unit", version.ref = "ui" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "foundation" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-core = { module = "androidx.core:core", version.ref = "core" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-monitor = { module = "androidx.test:monitor", version.ref = "monitor" }
androidx-navigation-common = { module = "androidx.navigation:navigation-common", version.ref = "navigation-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "navigation-compose" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle-viewmodel" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle-common" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "room-runtime" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup-runtime" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
com-google-android-material = { group = "com.google.android.material", name = "material", version.ref = "com-google-android-material-material" }
com-google-dagger = { module = "com.google.dagger:dagger", version.ref = "hilt" }
com-google-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "hilt" }
com-google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
com-google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
com-google-firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
com-google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
com-google-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
com-google-hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
com-jakewharton-timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
com-squareup-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
com-squareup-moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
com-squareup-moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
com-squareup-okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
com-squareup-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
com-squareup-okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
com-squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
io-mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk" }
io-mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
io-coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
org-jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
org-jetbrains-kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
org-jetbrains-kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
org-junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
org-junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-plugin" }
com-android-library = { id = "com.android.library", version.ref = "com-android-plugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
com-google-gms-google-services = { id = "com.google.gms.google-services", version = "4.3.15" }
com_github_ben-manes_versions = { id = "com.github.ben-manes.versions", version = "0.47.0" }
io_gitlab_arturbosch_detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.0" }
com_autonomousapps_dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.20.0" }
org_jetbrains_kotlinx_kover = { id = "org.jetbrains.kotlinx.kover", version = "0.7.1" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
com_osacky_doctor = { id = "com.osacky.doctor", version = "0.8.1" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
com-google-firebase-crashlytics-gradle = { id = "com.google.firebase.crashlytics", version = "2.9.5" }
[bundles]

