[versions]
activity-compose = "1.9.0"
coil-core = "3.0.0-alpha06"
com-android-plugin = "8.4.1"
core = "1.13.1"
android-sdk-target = "34"
android-min-sdk = "28"
google-services = "4.4.1"
kotlinx-serialization = "1.6.3"
lifecycle = "2.8.1"
material3-version = "1.6.10"
navigation-compose = "2.7.7"
navigation-compose-version = "2.7.0-alpha07"
sqlite = "2.4.0"
startup-runtime = "1.1.1"
compose = "1.6.7"
compose-plugin = "1.6.10"
kotlin = "2.0.0"
kotlinx-coroutines = "1.9.0-RC"
mockk = "1.13.11"
monitor = "1.6.1"
junit = "5.10.2"
timber = "5.0.1"
okhttp = "4.12.0"
material3 = "1.2.1"
ktor = "2.3.11"
koin = "3.6.0-Beta4"
sqldelight = "2.0.2"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity-compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
androidx-animation-core = { module = "androidx.compose.animation:animation-core", version.ref = "compose" }
androidx-compose-ui-android = { module = "androidx.compose.ui:ui-android", version.ref = "compose" }
androidx-compose-ui-graphics-android = { module = "androidx.compose.ui:ui-graphics-android", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling-android", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview-android", version.ref = "compose" }
androidx-compose-runtime-android = { module = "androidx.compose.runtime:runtime-android", version.ref = "compose" }
androidx-compose-foundation-android = { module = "androidx.compose.foundation:foundation-android", version.ref = "compose" }
androidx-compose-foundation-layout-android = { module = "androidx.compose.foundation:foundation-layout-android", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-core = { module = "androidx.core:core", version.ref = "core" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
androidx-monitor = { module = "androidx.test:monitor", version.ref = "monitor" }
androidx-navigation-common = { module = "androidx.navigation:navigation-common", version.ref = "navigation-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "navigation-compose" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup-runtime" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
androidx-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "compose" }
androidx-ui-unit = { module = "androidx.compose.ui:ui-unit", version.ref = "compose" }
app-cash-sqldelight-android-driver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
app-cash-sqldelight-coroutines-extensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }
app-cash-sqldelight-native-driver = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqldelight" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil-core" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil-core" }
coil-core = { module = "io.coil-kt.coil3:coil-core", version.ref = "coil-core" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor", version.ref = "coil-core" }
com-google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version = "22.0.0" }
com-google-firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version = "19.0.0" }
com-jakewharton-timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
com-squareup-okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
io-insert-koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
io-insert-koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
io-insert-koin-compose = { group = "io.insert-koin", name = "koin-compose", version = "1.2.0-Beta4" }
io-insert-koin-compose-viemodel = { group = "io.insert-koin", name = "koin-compose-viewmodel", version = "1.2.0-Beta4" }
io-ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
io-ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json" }
io-ktor-serialization-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation" }
io-ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
io-ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
io-ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
io-ktor-client-ios = { group = "io.ktor", name = "ktor-client-ios", version.ref = "ktor" }
io-ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
io-ktor-serialization = { module = "io.ktor:ktor-serialization", version.ref = "ktor" }
io-ktor-utils = { module = "io.ktor:ktor-utils", version.ref = "ktor" }
io-mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3-version" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose-version" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
org-jetbrains-kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
org-jetbrains-kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
org-jetbrains-kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
org-junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
org-junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-plugin" }
com-android-library = { id = "com.android.library", version.ref = "com-android-plugin" }
com-google-gms-google-services = { id = "com.google.gms.google-services", version = "4.4.1" }
com_github_ben-manes_versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
io_gitlab_arturbosch_detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.6" }
com_autonomousapps_dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.32.0" }
org_jetbrains_kotlinx_kover = { id = "org.jetbrains.kotlinx.kover", version = "0.8.0" }
com_osacky_doctor = { id = "com.osacky.doctor", version = "0.10.0" }
app-cash-sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
com-google-firebase-crashlytics-gradle = { id = "com.google.firebase.crashlytics", version = "3.0.1" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" }
org-gradle-android-cache-fix = { id = "org.gradle.android.cache-fix", version = "3.0.1" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dependency-guard = { id = "com.dropbox.dependency-guard", version = "0.5.0" }
dexcount = { id = "com.getkeepsafe.dexcount", version = "4.0.0" }
[bundles]

