name: Build release app

on:
  push:
    branches: [ "main", "master" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-home-cache-cleanup: true

      # Build debug app to improve pr check build speed by storing debug cache
      - name: Build debug apk
        run: ./gradlew :androidApp:assemble

      - name: Run detket plugin
        run: ./gradlew detektAll

      - name: Run ktlint plugin
        run: ./gradlew ktlintCheck

      - name: Run unit test
        run: ./gradlew testDebugUnitTest

      - name: Run dependency analysis android gradle plugin
        run: ./gradlew buildHealth
