name: Build release app

on:
  push:
    branches: [ "main" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.1
        with:
          gradle-home-cache-cleanup: true

      # Build debug app to improve pr check build speed by storing debug cache
      - name: Build debug apk
        run: ./gradlew androidApp:assembleDebug

      - name: Build release apk
        run: ./gradlew androidApp:assembleRelease

      - name: Run detket plugin
        run: ./gradlew detektAll

      - name: Run unit test
        run: ./gradlew testDebugUnitTest

      - name: Run dependency analysis android gradle plugin
        run: ./gradlew buildHealth
