name: Verify PR before margin to main

on:
  pull_request:
    branches: [ "main","master"]

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  gradle:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build apk
        run: ./gradlew :androidApp:assembleDebug

      - name: Run ktlint plugin
        run: ./gradlew ktlintCheck

      - name: Run detket plugin
        run: ./gradlew detektAll

      - name: Run android lint
        run: ./gradlew lint

      - name: Run ktlint format check
        run: ./gradlew ktlintCheck

      - name: Run unit test
        run: ./gradlew testDebugUnitTest

      - name: Run dependency analysis android gradle plugin
        run: ./gradlew buildHealth

      - name: Run gradle check
        run: ./gradlew check

      - name: Upload coverage reports
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.workspace }}/androidApp/build/reports/kover/report.xml
