name: Verify PR before margin to main

on:
  pull_request:
    branches: [ "main","master" ]

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  format:
    uses: ./.github/workflows/format.yml
  gradle:
    needs: [format]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build apk
        run: ./gradlew :androidApp:assembleDebug

      - name: Run ktlint plugin
        run: ./gradlew ktlintCheck

      - name: Run detket plugin
        run: ./gradlew detektAll

      - name: Run android lint
        run: ./gradlew lint

      - name: Run unit test
        run: ./gradlew testDebugUnitTest

      - name: Run dependency analysis android gradle plugin
        run: ./gradlew buildHealth

      - name: Run gradle check
        run: ./gradlew check

      - name: Check build-logic
        run: ./gradlew :build-logic:convention:check

      - name: Check presentation syncFramework
        run: ./gradlew :presentation:core:syncFramework -Pkotlin.native.cocoapods.configuration="Debug" -Pkotlin.native.cocoapods.platform="iphonesimulator" -Pkotlin.native.cocoapods.archs="arm64"

#      - name: Upload coverage reports
#        id: kover
#        uses: mi-kas/kover-report@v1
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          path: ${{ github.workspace }}/androidApp/build/reports/kover/reportCustom.xml
